# Generated by Django 3.1.7 on 2021-03-01 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonenumber', models.IntegerField(max_length=9, verbose_name='Номер')),
                ('firstname', models.CharField(max_length=30, verbose_name='Имя')),
                ('lastname', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('middlename', models.CharField(max_length=30, verbose_name='Отчество')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
                ('adress', models.CharField(max_length=100, verbose_name='Адрес')),
            ],
        ),
        migrations.CreateModel(
            name='PhonesView',
            fields=[
                ('phone_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='phones.phone')),
            ],
            bases=('phones.phone',),
        ),
    ]
